package kvstore

const OPERATION_GET = "GET"
const OPERATION_SET = "SET"
const OPERATION_DELETE = "DELETE"

const RESPONSE_OK = "OK"
const RESPONSE_KEY_NOT_FOUND = "ERROR: KEY NOT FOUND"
const RESPONSE_INVALID_REQUEST = "ERROR: INVALID REQUEST"
